name: Release Drafter

on:
    push:
        branches: [master]
    pull_request:
        types: [opened, reopened, synchronize]

permissions:
    contents: write
    pull-requests: write

jobs:
    draft-release:
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@6081f1663ce210c48547e197dce48450a93e7b3f # v7.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
